version: '2.1'
services:

  queue:
    image: redis
    ports:
      - "6379:6379"

  rdsviewer:
    image: tenstartups/redis-commander
    ports:
      - "8081:8081"
    command:
        - --redis-host=queue
    links:
      - queue

  elk:
    build:
      context: .
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "5000:5000"
    links:
      - queue